{% set name = "google-cloud-translate" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cd957f4b29a8c7a983e0a427c2712533c41bb7007b76a8cc88d6c65075c679a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose
  skip: true  # [win and vc<14]

requirements:
  host:
    - python
    - pip >=18.1
    - google-api-core-grpc >=1.22.2,<2.0.0dev
    - google-cloud-core >=1.3.0,<2.0.0dev
    - proto-plus >=0.4.0
    - packaging >=14.3
  run:
    - python
    - google-api-core-grpc
    - google-cloud-core
    - proto-plus
    - packaging

test:
  imports:
    - google.api
    - google.api_core
    - google.cloud.client
    - google.cloud.environment_vars
    - google.cloud.exceptions
    - google.cloud.obsolete
    - google.cloud.operation
    - google.cloud.translate
    - google.cloud.translate_v2
    - google.cloud.translate_v2._http
    - google.cloud.translate_v2.client
    - google.cloud.translate_v3beta1
    - google.cloud.translate_v3beta1.gapic
    - google.cloud.translate_v3beta1.gapic.translation_service_client
    - google.cloud.translate_v3beta1.gapic.translation_service_client_config
    - google.cloud.translate_v3beta1.gapic.transports
    - google.cloud.translate_v3beta1.gapic.transports.translation_service_grpc_transport
    - google.cloud.translate_v3beta1.proto
    - google.cloud.translate_v3beta1.proto.translation_service_pb2
    - google.cloud.translate_v3beta1.proto.translation_service_pb2_grpc
    - google.cloud.translate_v3beta1.types
    - google.cloud.translate_v3
    - google.longrunning
    - google.oauth2
    - google.protobuf
    - google.rpc
    - grpc

about:
  home: https://github.com/googleapis/google-cloud-python
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Translation
  description: |
    Python Client for Google Cloud Translation
    -------------------------

    With [Google Cloud Translation]( https://cloud.google.com/translate/), you can dynamically translate text between
    thousands of language pairs. The Google Cloud Translation API lets websites
    and programs integrate with Google Cloud Translation programmatically. Google
    Cloud Translation is available as a paid service. See the [Pricing](https://cloud.google.com/translate/pricing) and
    [FAQ](https://cloud.google.com/translate/faq) pages for details.

    - [Client Library Documentation](https://googleapis.github.io/google-cloud-python/latest/translate/usage.html)
    - [Product Documentation](https://cloud.google.com/translate/docs)

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -----------
    Python >= 3.5

    Deprecated Python Versions
    -----------
    Python == 2.7. Python 2.7 support will be removed on January 1, 2020.

  doc_url: https://googleapis.github.io/google-cloud-python/latest/translate/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/master/translate

extra:
  recipe-maintainers:
    - BrentDorsey
    - parthea
