{% set name = "google-cloud-translate" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7da158734db646867deb125c144a7a1692a48a134692c4dc54ba420f89db64ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - google-api-core-grpc
    - google-cloud-core
    - proto-plus
    - packaging
  run:
    - python >=3.6
    - pip >=18.1
    - google-api-core-grpc >=1.26.0,<3.0.0dev
    - google-cloud-core >=1.3.0,<3.0.0dev
    - proto-plus >=1.4.0
    - packaging >=14.3
test:
  imports:
    - google.cloud.translate
    - google.cloud.translate_v2
    - google.cloud.translate_v3beta1
    - google.cloud.translate_v3
    - grpc

about:
  home: https://github.com/googleapis/google-cloud-python
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Translation
  description: |
    Python Client for Google Cloud Translation
    -------------------------

    With [Google Cloud Translation]( https://cloud.google.com/translate/), you can dynamically translate text between
    thousands of language pairs. The Google Cloud Translation API lets websites
    and programs integrate with Google Cloud Translation programmatically. Google
    Cloud Translation is available as a paid service. See the [Pricing](https://cloud.google.com/translate/pricing) and
    [FAQ](https://cloud.google.com/translate/faq) pages for details.

    - [Client Library Documentation](https://googleapis.dev/python/translation/latest/index.html)
    - [Product Documentation](https://cloud.google.com/translate/docs)

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -----------
    Python >= 3.6

  doc_url: https://googleapis.dev/python/translation/latest/index.html
  dev_url: https://github.com/googleapis/python-translate

extra:
  recipe-maintainers:
    - BrentDorsey
    - parthea
