travis:
  secure:
    BINSTAR_TOKEN: XUhEXEv1AnDqp7uBErdZuPLUCWMdc0CkdyT13gMK+w0xvVwrNGQ7voVAlfxwVmD/T3tWTTXHfL4i4BCvMuqqsTNbCxk52dP97V/gFmcw9Dcjfaay2KLv1XIc8Nd3CVj4f6opFnzLW6j8515DotrH1JrUyqHxs6VQQC+TdFvtKayd0C+3I5n9qHJGhxF0AH+zr1orSkiGB/DGiV9l46yKdqkfxlhvFjz6rE6zK3R1px7yrhiXPoD3VHrpNOIkyjE70q3VKrXNDFIRat1IznXKWi15SBRLp9+TuI245aRXrJZSccPYkQjDYGYy63YCTLeKik7e9dcmoCOvJrHdyF+Rclt/mBwcMgkujyBiPvRcxNY6VrAOJdEyvkgzJKFMnTB/fIMhkr7mtkbTMaT16bT3DraoQwxqnU3TBGodVHFySEYzeUNNmidwhqfWEXBsM9ssuo8+otBQdJyfTZ0oIBabkKLaIACuwd8bVmujoOQxDgnA1AshhKi65NcakoK1dAYmt4y3HtLIgxlXpWrBbrLpo8w7Jrq+pmuvXUG9XGJRbwVaysNowi4KiI+MDc16634Ux03Zgxq2mC6jVvkzjXBSXd11tM9LBMcmyD3Rq9OGYIOotEHNTsOFG80Fe2JOnNEb8ueeDKUxSdUZFGa263AzCmnFB5WKijLDRl/Y4B5ym70=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
